version: "3"
services:
  redis:
    image: "bitnami/redis"
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  web:
    build: .
    environment:
      - MIX_ENV=dev
      - REDIS_URI=redis://redis:6379
    ports:
      - "4000:4000"
    volumes:
      - .:/app
